config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'articles/create'
  get 'articles/edit'
  get 'articles/update'
  get 'articles/edit'
  get 'articles/destroy'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                   length: { minimum: 5 }
  has_one_attached :song_file
  geocoded_by :region
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
   @articles = Article.all
  end

  def new
   @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
     redirect_to @article
   else
     render 'new'
   end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])

  end

  def update
    @article = Article.find(params[:id])
    if @article.update(student_params)
      redirect_to @article
  else
    render 'edit'
  end
  end

  def edit
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

 redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :description, :region, song_file: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :descrpition %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :region %><br>
    <%= form.text_area :region %>
  </p>
  <p>
    <%= form.label "Audio File" %><br>
    <%= form.file_field :song_file, multiple: true, direct_upload: true %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>
<%= render 'form' %>
    <%= link_to 'Back', article_path %>

app/views/articles/index.html.erb
    <style>
       /* Set the size of the div element that contains the map */
      #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
    </style>
  </head>
  <body>
    <h3>My Google Maps Demo</h3>
    <!--The div element for the map -->
    <div id="map"></div>
    <script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});

}
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API'] %>&callback=initMap">
    </script>
  </body>
</html>





<table>
  <tr>
    <th>Title</th>
    <th>description</th>
    <th>region</th>
    <th>song_file</th>

    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><span onclick="openPage<%= article.id%>()"><%= article.title %></span></td>
      <td><%= article.description %></td>
      <td><%= article.region %></td>
      <td><%= link_to 'play', new_article_path %></td>
<!-- each side pages -->
      <div id="sidePage<%= article.id%>" class="side" style="width: 0px;">
      <a href="javascript:void(0)" class="xbutton" onclick="closePage<%= article.id%>()">&times;</a>
      <p>this is where music will play and comments and add donation button and NGO project</p>
      <strong>Title: <%=article.title %></strong>
      <strong>Description: <%=article.description %></strong>
      <strong>Region: <%=article.region %></strong>

      <td > <p id="sidecontent">  </p> </td>

      </div>

      <script>
      function openPage<%= article.id%>() {
          document.getElementById("sidePage<%= article.id%>").style.width = "40%";
      }

      function closePage<%= article.id%>() {
          document.getElementById("sidePage<%= article.id%>").style.width = "0";
      }
      </script>
  <% end %>
</table>
<script
   src="https://code.jquery.com/jquery-3.2.1.min.js"
   integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
   crossorigin="anonymous"></script>





 <button>listen</button>
 <%= link_to 'New article', new_article_path %>

 <p>tests</p>
 <p>

app/views/articles/new.html.erb
<h1>Articles#new  list of music</h1>
<p>Find me in app/views/articles/new.html.erb</p>
<%= render  'articles/form' %>
<%= link_to 'Back', articles_path() %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>region:</strong>
  <%= @article.region %>
</p>

<p>
  <strong>song_file:</strong>
  <button><%= link_to "Play Song", @article.song_file, class: "html5" %></button>
</p>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  'application.js', "https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'musiclist', articles_path %>